title="Logbook"
slug="logbook"
permalink="/logbook"
content="""

## QRZ Logbook Summary

This page was last updated on 2025-10-26 13:23:06 +0000

<!-- 2025-10-26 13:23:06 +0000 -->
<table class="logbook"><thead><tr>
<th>Date</th>
<th>Callsign</th>
<th>Band</th>
<th>Mode</th>
<th>Grid</th>
<th>Country</th>
<th>Operator</th>
<!--<th>Comment</th>-->
</tr></thead><tbody>
<tr>
<td><date>2025-05-03</date></td>
<td><a itescope itemtype="https://schema.org/callSign" href="https://qrz.com/db/SY1AWR">SY1AWR</a></td>
<td>2m</td>
<td>FM</td>
<td></td>
<td>Greece</td>
<td></td>
<!--<td></td>-->
</tr>
</tbody></table>
"""
