title = "Kent Spring Half Mar-19th-mar-2026"
slug = "kent-spring-half-mar"
date = 2026-04-29
tags = ["raynet"]

summary="A standard half mar"

content = """
No drama this time, except that I was a little late getting up.
I didn't make it to the briefing point in time, but I got to my
marshall point about 10 minutes before the race began.

<div id="map"></div>

Single radio, the Quangsheng, split frequency operation on the MB9ABH repeater. The signal
was touch and go - at times it was perfect, and at other times there was QRN that meant
I couldn't get a word.

I nipped around the Ashford Golf Club for a coffee when there was a lull in
the race. The staff are surely not accustomed to serving yellow-vested radio-totting
bearded patrons. Snotty service, which I can forgive, horrible coffee, which I cannot.

I just realised something as I was writing this blog post. I was looking
for the coordinates for my marshall point, M3. Only I wasn't there. I was at M2,
which was just around the corner. What can I say - changes in personal life (the
good kind) must have made me a little absent-minded. I've marked both positions on
the map so you can see where I was versus where I should have been.

The drive to Ashford was wonderful. A sunny and mildly windy day, and a slight delay
in leaving the house, meant that I could ride in a manner that riders call "spirited".
That means you still respect the limits around villages - you don't want to a) get
a reputation with the locals, or b) see any yellow cameras sprout up - but nationals
are fair game. And fair game they were.

The marshalls were lovely. I didn't get their names but they were gentle people, former
runners themselves. After the race I went back home, in a less spirited but _still_ spirited
fashion, and went on with my day.

<script>
const markers = [
  {
    lat: 51.170667,
    lon: 0.852727,
    popupContent: "<b>M2</b>"
  },
  {
    lat: 51.171727,
    lon: 0.850965,
    popupContent: "<b>M3</b>"
  }
]

const firstMarker = markers[0];
var map = L.map('map').setView([firstMarker.lat, firstMarker.lon], 16);
L.tileLayer('http://sgx.geodatenzentrum.de/wmts_topplus_open/tile/1.0.0/web_grau/default/WEBMERCATOR/{z}/{y}/{x}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);
markers.forEach(mark => L.marker(mark).addTo(map).bindPopup(mark.popupContent))
</script>
"""
