#!/bin/bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cat <<EOF
title="Logbook"
slug="logbook"
permalink="/logbook"
content="""

## QRZ Logbook Summary

This page was last updated on $(date +"%Y-%m-%d %T %z" )

$(bash ${__dir}/get-logbook ${1})
"""
EOF
